spring.application.name=Carrera
#Puerto
server.port=9001

#Configuración de la BD
spring.datasource.url=jdbc:mysql://localhost:3306/carreras
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#URL de la API "competidor" a la cual WebClient se conectará para hacerle peticiones
api.url.competidor=http://localhost:9000/api/competidor

#URL de la API "categoria" a la cual WebClient se conectará para hacerle peticiones
api.url.categoria=http://localhost:9002/api/categoria
