spring.application.name=Competidor
#Puerto
server.port=9000

#Datos de la BD SQL
spring.datasource.url=jdbc:mysql://localhost:3306/microservicios
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
