spring.application.name=Competidor
#Puerto
server.port=9000

#Configuración de la BD
spring.datasource.url=jdbc:mysql://localhost:3306/competidores
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

//URL de la API "carrera" a la cual WebClient se conectará para hacerle peticiónes 
api.url.carrera=http://localhost:9001/api/carrera
